services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: irmos
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: actual_bridge
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      DATABASE_URL: postgresql://irmos:pwd123@db:5432/actual_bridge
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db_data: